### ISSUE TITLE
@jbrowse/cli vs @gmod/jbrowse-cli

### ISSUE THREAD

**Issue by uludag** [laceysanderson/jbrowse2play#1]
Dear @laceysanderson,

I was trying to write a Docker file for JBrowse2 based on your example Docker files; I was getting unclear errors when I was trying to open my JBrowse home page after building and running my JBrowse Docker image. I later realized that [there are two different jbrowse/cli packages in npmjs repository](https://www.npmjs.com/search?q=jbrowse%2Fcli), one called @jbrowse/cli, the other called @gmod/jbrowse-cli, later one was not updated in the last 8 months. The following list of JBrowse versions were printed when I added `RUN jbrowse create --listVersions` line to my Dockerfile.

> All JBrowse versions: @gmod/jbrowse-web@v0.0.1-testrelease.2, @gmod/jbrowse-web@v0.0.1-testrelease.1, @gmod/jbrowse-web@0.0.1-beta.24, @gmod/jbrowse-web@0.0.1-beta.25, @gmod/jbrowse-web@0.0.1-beta.23, @gmod/jbrowse-web@0.0.1-beta.15

After moving to the @jbrowse/cli package, I stopped getting the unclear error messages, and my JBrowse instance looks working as expected.
--mahmut

**Comment by laceysanderson** [comment]
Hmmmmm.... interesting! This must have changed on me -thank you for letting me know so I can update my image!

PS. If you would like to make a PR to my repository with this change so you get credit for this work I would be happy to accept it! :-)

**Comment by uludag** [comment]
Thanks, I have tried making a pull request. Building the Docker images required to update the version of the installed nodejs in two Docker files. For the image devJBrowse the _jbrowse-web_ folder was in a different folder than given in the readme file, I have updated the readme file with the correct folder name!
